remote_theme: cnheider/Moon

title: 'Neodroid Landing'
logo: 'assets/img/logo.png'
background: ''
url: 'http://neodroid.ml'

jekyll-mentions:
  base_url: https://github.com

plugins:
  - jekyll-redirect-from
  - jekyll-remote-theme


exclude: [vendor,README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]

